version: '3.8'

services:
  # Servicio de la aplicación NestJS
  app:
    build: .
    container_name: nestjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin123
      - DB_DATABASE=graphql_ap
    depends_on:
      - postgres
      - rabbitmq

  # Servicio de PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=graphql_ap
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Servicio de RabbitMQ
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-server
    ports:
      - "15672:15672" # Interfaz de administración
      - "5672:5672"   # Puerto de mensajería
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

volumes:
  postgres-data:
